-- title:   Mr Anderson's Adventure
-- author:  Zsolt Tasnadi
-- desc:    Life of a programmer in the Vector
-- site:    https://github.com/rastasi/mranderson
-- license: MIT License
-- version: 0.10
-- script:  lua
